SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

MAX_FPS = 60

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_BASE_SHOOT_SPEED = 500
PLAYER_WEAPON_COOLDOWN = 0.15
PLATER_BOOSTER_FACTOR = 1.5

SHOT_RADIUS = 5
SHOT_LINE_WIDTH = 0

RESOURCE_BAR_PADDING = 10
RESOURCE_BAR_WIDTH = SCREEN_WIDTH / 5
RESOURCE_BAR_HEIGHT = 30